[toolchain]
anchor_version = "0.32.1"
solana_version = "2.3.0"

[features]
resolution = true
skip-lint = false

[programs.mainnet]
solforge_game = "F4rUAeBfjpeV5SLQJv6BCNhSr4QrignBDxFEzTU7bPyp"

[programs.devnet]
solforge_game = "F4rUAeBfjpeV5SLQJv6BCNhSr4QrignBDxFEzTU7bPyp"

[provider]
cluster = "Mainnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "anchor test"
