[package]
name = "solforge-game"
version = "0.1.0"
description = "On-chain state program for SolForge Tycoon"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "solforge_game"

[features]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
cpi = ["no-entrypoint"]
default = []

[dependencies]
anchor-lang = "0.32.1"
anchor-spl = { version = "0.32.1", features = ["token"] }
